masthead_title: Trevor Lauder – DevOps, Code & Photography
description: DevOps and SRE topics—automation, monitoring, tooling—plus a personal mix of coding projects, photography, and astrophotography.
minimal_mistakes_skin: custom
search: true
favicon: /assets/images/favicon.ico
url: https://www.lauder.family
baseurl: /
repository: lauderfamily/lauderfamily.github.io
og_image: /assets/images/og.webp
teaser: /assets/images/teasers/default.svg

formspree: mbjqwvgk
contact_page_description: Have any questions about the content on this page?  You are welcome to contact me using the form below!
thankyou_page_description: Your message has been successfully sent.

markdown: kramdown
theme: minimal-mistakes-jekyll

permalink: pretty
timezone: Canada/Mountain

pagination:
  enabled: true

exclude:
  - node_modules
  - scripts
  - package.json
  - package-lock.json

include:
  - _pages

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: Trevor Lauder
  avatar: /assets/images/authorimage.webp
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/trevorlauder
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/trevor-lauder

social:
  links:
    - https://github.com/trevorlauder
    - https://www.linkedin.com/in/trevor-lauder

analytics:
  provider: google-gtag
  google:
    tracking_id: G-1F9WKFBP24

footer:
  since: 2021
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/trevorlauder
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/trevor-lauder

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: giscus
  giscus:
    repo_id: R_kgDOGHVffw
    category_name: Announcements
    category_id: DIC_kwDOGHVff84CpXAy
    discussion_term: pathname
    reactions_enabled: 1
    theme: https://www.lauder.family/assets/css/giscus-dark.css

facebook:
  app_id: 856768292162027
