name: Site CI

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build --trace

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
